// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: discussion.proto

// Protobuf Java Version: 3.25.1
package rs.raf.grpc;

public final class DiscussionServiceProto {
  private DiscussionServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewTopicRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NewTopicRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewCommentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NewCommentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommentReplyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommentReplyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommentUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommentUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommentDeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommentDeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopicsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TopicsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopicsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TopicsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopicCommentsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TopicCommentsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopicCommentsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TopicCommentsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020discussion.proto\"1\n\017NewTopicRequest\022\r\n" +
      "\005title\030\001 \001(\t\022\017\n\007comment\030\002 \001(\t\"\034\n\010Respons" +
      "e\022\020\n\010response\030\001 \001(\t\"3\n\021NewCommentRequest" +
      "\022\r\n\005topic\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\"N\n\023Comm" +
      "entReplyRequest\022\r\n\005topic\030\001 \001(\t\022\017\n\007messag" +
      "e\030\002 \001(\t\022\027\n\017parentCommentId\030\003 \001(\005\"I\n\024Comm" +
      "entUpdateRequest\022\r\n\005topic\030\001 \001(\t\022\017\n\007messa" +
      "ge\030\002 \001(\t\022\021\n\tcommentId\030\003 \001(\005\"8\n\024CommentDe" +
      "leteRequest\022\r\n\005topic\030\001 \001(\t\022\021\n\tcommentId\030" +
      "\002 \001(\005\"\017\n\rTopicsRequest\" \n\016TopicsResponse" +
      "\022\016\n\006topics\030\001 \003(\t\"%\n\024TopicCommentsRequest" +
      "\022\r\n\005topic\030\001 \001(\t\"5\n\017CommentResponse\022\017\n\007me" +
      "ssage\030\001 \001(\t\022\021\n\tcommentId\030\002 \001(\005\";\n\025TopicC" +
      "ommentsResponse\022\"\n\010comments\030\001 \003(\0132\020.Comm" +
      "entResponse2\330\003\n\nDiscussion\022-\n\014SendNewTop" +
      "ic\022\020.NewTopicRequest\032\t.Response\"\000\0228\n\025Sen" +
      "dNewCommentToTopic\022\022.NewCommentRequest\032\t" +
      ".Response\"\000\0223\n\016ReplyToComment\022\024.CommentR" +
      "eplyRequest\032\t.Response\"\000\0225\n\017UpdateMyComm" +
      "ent\022\025.CommentUpdateRequest\032\t.Response\"\000\022" +
      "5\n\017DeleteMyComment\022\025.CommentDeleteReques" +
      "t\032\t.Response\"\000\0222\n\rGetTopicsList\022\016.Topics" +
      "Request\032\017.TopicsResponse\"\000\022C\n\020GetTopicCo" +
      "mments\022\025.TopicCommentsRequest\032\026.TopicCom" +
      "mentsResponse\"\000\022E\n\022GetRandomCommentId\022\025." +
      "TopicCommentsRequest\032\026.TopicCommentsResp" +
      "onse\"\000B-\n\013rs.raf.grpcB\026DiscussionService" +
      "ProtoP\001\242\002\003HLWb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_NewTopicRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NewTopicRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NewTopicRequest_descriptor,
        new java.lang.String[] { "Title", "Comment", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_NewCommentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_NewCommentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NewCommentRequest_descriptor,
        new java.lang.String[] { "Topic", "Message", });
    internal_static_CommentReplyRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CommentReplyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommentReplyRequest_descriptor,
        new java.lang.String[] { "Topic", "Message", "ParentCommentId", });
    internal_static_CommentUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CommentUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommentUpdateRequest_descriptor,
        new java.lang.String[] { "Topic", "Message", "CommentId", });
    internal_static_CommentDeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_CommentDeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommentDeleteRequest_descriptor,
        new java.lang.String[] { "Topic", "CommentId", });
    internal_static_TopicsRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_TopicsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TopicsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_TopicsResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_TopicsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TopicsResponse_descriptor,
        new java.lang.String[] { "Topics", });
    internal_static_TopicCommentsRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_TopicCommentsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TopicCommentsRequest_descriptor,
        new java.lang.String[] { "Topic", });
    internal_static_CommentResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_CommentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommentResponse_descriptor,
        new java.lang.String[] { "Message", "CommentId", });
    internal_static_TopicCommentsResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_TopicCommentsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TopicCommentsResponse_descriptor,
        new java.lang.String[] { "Comments", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
