// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: discussion.proto

// Protobuf Java Version: 3.25.1
package rs.raf.grpc;

public interface TopicsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TopicsRequest)
    com.google.protobuf.MessageOrBuilder {
}
