// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: discussion.proto

// Protobuf Java Version: 3.25.1
package rs.raf.grpc;

public interface TopicCommentsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TopicCommentsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .CommentResponse comments = 1;</code>
   */
  java.util.List<rs.raf.grpc.CommentResponse> 
      getCommentsList();
  /**
   * <code>repeated .CommentResponse comments = 1;</code>
   */
  rs.raf.grpc.CommentResponse getComments(int index);
  /**
   * <code>repeated .CommentResponse comments = 1;</code>
   */
  int getCommentsCount();
  /**
   * <code>repeated .CommentResponse comments = 1;</code>
   */
  java.util.List<? extends rs.raf.grpc.CommentResponseOrBuilder> 
      getCommentsOrBuilderList();
  /**
   * <code>repeated .CommentResponse comments = 1;</code>
   */
  rs.raf.grpc.CommentResponseOrBuilder getCommentsOrBuilder(
      int index);
}
