apiVersion: apps/v1
kind: Deployment
metadata:
  name: discussion-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: discussion-server
  template:
    metadata:
      labels:
        app: discussion-server
    spec:
      containers:
        - name: discussion-server
          image: nocni/discussion-system
          ports:
            - containerPort: 8090
            - containerPort: 8091
            - containerPort: 8092
          args: ["java", "--add-opens", "java.base/java.lang=ALL-UNNAMED", "-cp", "Projekat-1.0-SNAPSHOT.jar:lib/*", "rs.raf.DiscussionServer", "/tmp/server", "account", "127.0.0.1:8090", "127.0.0.1:8090,127.0.0.1:8091,127.0.0.1:8092", "8090"]